- type: entity
  abstract: true
  parent: Clothing
  id: ClothingUnderwearBottomBase
  components:
  - type: Sprite
    state: icon
  - type: Item
    size: Tiny
  - type: Clothing
    slots: [underwearb]
  - type: Butcherable
    butcheringType: Knife
    spawned:
    - id: MaterialCloth1
      amount: 1
  - type: Food
    requiresSpecialDigestion: true
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 10
        reagents:
        - ReagentId: Fiber
          Quantity: 10
  - type: Tag
    tags:
    - underwearb
    - ClothMade
  - type: StealTarget
    stealGroup: Panties

- type: entity
  abstract: true
  parent: Clothing
  id: ClothingUnderwearTopBase
  components:
  - type: Sprite
    state: icon
  - type: Item
    size: Tiny
  - type: Clothing
    slots: [underweart]
  - type: Butcherable
    butcheringType: Knife
    spawned:
    - id: MaterialCloth1
      amount: 1
  - type: Food
    requiresSpecialDigestion: true
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 10
        reagents:
        - ReagentId: Fiber
          Quantity: 10
  - type: Tag
    tags:
    - underweart
    - ClothMade

- type: entity
  abstract: true
  parent: Clothing
  id: ClothingUnderwearSocksBase
  components:
  - type: Sprite
    state: icon
  - type: Item
    size: Tiny
  - type: Clothing
    slots: [socks]
  - type: Butcherable
    butcheringType: Knife
    spawned:
    - id: MaterialCloth1
      amount: 1
  - type: Food
    requiresSpecialDigestion: true
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 10
        reagents:
        - ReagentId: Fiber
          Quantity: 10
  - type: Tag
    tags:
    - socks
    - ClothMade
