#Рюкзак офицера
- type: entity
  noSpawn:  false
  parent: ClothingBackpackSatchelGenetics
  id: ClothingBackpackSatchelOfficerBlueShield
  components:
  - type:  StorageFill
    contents:
      - id: BoxSurvivalSecurity
      - id: Flash


#Пояс офицера
-   type: entity
    id: ClothingBeltAssaultFilled
    parent: ClothingBeltAssault
    suffix: Filled
    components:
    - type: StorageFill
      contents:
        - id: Stunbaton
        - id: Handcuffs
        - id: Handcuffs
        - id: GrenadeFlashBang
        - id: GrenadeFlashBang


#ID карта офицера
- type: entity
  parent: CentcomIDCard
  id: OfficerBlueShieldIDcard
  name: Officer BlueShield ID card
  components:
  - type: Sprite
    layrs:
    - state: blue
    - state: idcentcom
  - type: Item
    heldPrefix: blue


#PDA офицера
- type: entity
  parent: ERTLeaderPDA
  id: OfficerBlueShieldPDA
  name: Officer BlueShield PDA
  description: I'm Blue Da ba dee da ba dye
  components:
    - type: Pda
      id: OfficerBlueShieldIDcard
      state: pda-ert
    - type: PdaBorderColor
      borderColor: "#000000"
      accentHColor: "#8b0000"



- type: startingGear
  id: OfficerBlueShield
  equipment:
    jumpsuit: ClothingUniformJumpsuitSecBlue
    back: ClothingBackpackSatchelOfficerBlueShield
    shoes:  ClothingShoesBootsCombat
    head: ClothingHeadHatERTLeaderBeret
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesCombat
    outerClothing:  ClothingOuterVestWeb
    ears: ClothingHeadsetCommand
    belt: ClothingBeltAssaultFilled
    id: OfficerBlueShieldPDA
    pocket1:  WeaponDisabler
    pocket2:  Handcuffs
