contact_links:
  - name: Предложение
    url: https://discord.com/invite/CPacm3dfrA
    about: Свои предложения можете оставлять в соответствующем канале Discord.
  - name: Сообщить об уязвимости
    url: https://discord.com/invite/CPacm3dfrA
    about: Пожалуйста, сообщайте о серьезных эксплойтах и уязвимостях безопасности lemird (634710558364663819) или 13lackhawk (236910741146304515) в Discord.
