- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Aspid
  #- Bagel
  - Box
  - Cluster
  # CorvaxDelta
  - Fland
  #- Core
  - Meta
  - Marathon
  - Origin
  - Kettle
  - Omega
  - Saltern
  - Packed
