- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Bagel
  - Aspid
  - Atlas
  - CorvaxSilly
# - Barratry
  - Box
  - CorvaxSpectrum
#  - Cluster
  - CorvaxAvrite
  - Meta
  - CorvaxOutpost
  - CorvaxDelta
# - Origin
  - Gemini
#  - Marathon
#  - Core
  - Fland
# - Kettle
  - Omega
  - Reach
  - Saltern
  - Packed
