- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Aspid
  - Bagel
  - Box
  - Cluster
  - Core
  #- Fland
  - Kettle
  - Marathon
  - Meta
  - Omega
  - Origin
  - Saltern
  - Packed
  - CorvaxDelta
