- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Atlas
  - Omega
  - Bagel
# - Barratry
  - Box
  - CorvaxSpectrum
#  - Cluster
#  - CorvaxAvrite
  - CorvaxAstra
  - Marathon
  - Meta
  - Fland
  - Core
#  - CorvaxDelta
#  - CorvaxOutpost
# - Origin
  - CorvaxSilly
  - Saltern
  - Packed
  - Reach
