- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Bagel
  - Aspid
  - Atlas
# - Barratry
  - Box
  - CorvaxSpectrum
  - Cluster
  - CorvaxDelta
# - Origin
  - Gemini
  - Marathon
  - Core
  - Meta
  - Fland
# - Kettle
  - Omega
  - Saltern
  - Packed
