- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Aspid
  #- Bagel
  - Box
  - CorvaxSpectrum
  - Cluster
  - CorvaxDelta
  - Origin
  - Marathon
  - Fland
  #- Core
  - Meta
  - Kettle
  - Omega
  - Saltern
  - Packed
