- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Aspid
  #- Bagel
  - CorvaxSpectrum
  - Box
  - Cluster
  - CorvaxDelta
  - Origin
  - Fland
  #- Core
  - Marathon
  - Meta
  - Marathon
  - Kettle
  - Omega
  - Saltern
  - Packed
