- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Bagel
  - Aspid
  - Box
  - CorvaxSpectrum
  - Cluster
  - CorvaxDelta
#  - Origin
  - Kettle
  - Meta
  - Marathon
  - Fland
  #- Core
  - Omega
  - Saltern
  - Packed
