- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Aspid
  - Atlas
  - CorvaxSilly
  - Bagel
# - Barratry
  - Box
  - CorvaxSpectrum
#  - Cluster
#  - CorvaxAvrite
  - Fland
  - Core
  - Gemini
  - Meta
#  - CorvaxDelta
  - CorvaxOutpost
# - Origin
  - Marathon
  - Omega
  - Saltern
  - Packed
  - Reach
