- type: entity
  name: Loyalty implanter box
  parent: BoxCardboard
  id: BoxLoyaltyImplanter
  description: A box of Loyalty implanters.
  components:
    - type: StorageFill
      contents:
        - id: LoyaltyImplanter
          amount: 6
    - type: Sprite
      layers:
        - state: box_security
