- type: job
  id: Magistrate
  name: job-name-magistrate
  playTimeTracker: JobMagistrate
  requirements:
    - !type:DepartmentTimeRequirement
      department: Command
      time: 54000 
    - !type:RoleTimeRequirement
      role: JobIAA
      time: 36000 
  startingGear: MagistrateGear
  icon: "NanoTrasen"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess

- type: startingGear
  id: MagistrateGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitLawyerBlack
    shoes: ClothingShoesBootsLaceup
    head: ClothingHeadHatPwig
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesColorWhite
    outerClothing: ClothingOuterRobesJudge
    id: CentcomPDA
    ears: ClothingHeadsetAltCommand
    neck: ClothingNeckLawyerbadge
    pocket1: BookEscalationSecurity
    pocket2: ClothingNeckNanoTrasenPin