- type: antag
  id: Nukeops
  name: roles-antag-nuclear-operative-name
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-objective

# Turned off so sponsor shit can work
#- type: antag
#  id: NukeopsMedic
#  name: roles-antag-nuclear-operative-agent-name
#  antagonist: true
#  setPreference: true
#  objective: roles-antag-nuclear-operative-agent-objective

- type: antag
  id: NukeopsCommander
  name: roles-antag-nuclear-operative-commander-name
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-commander-objective
