ent-WeaponRifleAk = AKMS
    .desc = An iconic weapon of war. Uses .30 винтовочный.
ent-WeaponXrayCannon = EarthGov Experemental X-Ray
    .desc = A Earth Government Experemental x-ray weapon, it looks like it emits radiation.
ent-WeaponLaserCarbine = EarthGov laser rifle
    .desc = A Earth Government standard issue laser rifle, use by army and police.
ent-WeaponLaserCannon = EarthGov heavy laser rifle
    .desc = A Earth Government heavy sniper rifle for a extended combat situation.
ent-WeaponRifleLecter = AR-18
    .desc = The H&K AR-18 carbine is one of the standard rifles used by EarthGov army. It's commonly used by people who prefer greater mobility in combat, like scouts and other light infantry.
ent-WeaponSubMachineGunAtreides = MP7
    .desc = An archaic design going back hundreds of years, the SMG-7 was common in its day. Today it sees limited use as cheap computer-printed replicas or family heirlooms, though it somehow got into the hands of colonial rebels.
ent-WeaponPistolViper = HI Browning-88 M4
    .desc = An uncommon handgun used for self-defense but it is often used by terrorist organizations.
ent-WeaponPistolMk58 = ACP-14
    .desc = The ACP-14, produced by Earth Armories. A reliable sidearm that loads .35 авто.
ent-WeaponPistolMk58Nonlethal = G-22
    .desc = A popular police firearm in the modern day. Chambered in .35 авто.
ent-WeaponSubMachineGunDrozd = Vector
    .desc = The Vector used by police special force. Chambered in .35 авто.
ent-WeaponSubMachineGunDrozdRubber = MP5
    .desc = The RivArms SMG-5 submachinegun, an update to a classic design. A light firearm capable of effective one-handed use that is ideal for close to medium range engagements.
