name: Prevent RSI Diff Action

on:
  workflow_call:

jobs:
  prevent-rsi-diff:
    name: Prevent RSI Diff Action
    runs-on: ubuntu-latest
    steps:
      - name: Check for RSI Diff Action
        uses: actions/github-script@v6
        with:
          script: |
            const workflow = github.context.payload.workflow;
            const jobs = workflow.jobs;

            for (const jobName in jobs) {
              const job = jobs[jobName];
              const steps = job.steps;

              for (const step of steps) {
                if (step.uses === 'space-wizards/RSIDiffBot@v1.1') {
                  throw new Error('The RSI Diff Action is not allowed in this workflow.');
                }
              }
            }